name: event_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  share_plus: ^10.0.3

  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  url_launcher: ^6.3.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/onboarding_community_events.png
    - assets/images/onboarding_illustration.png
    - assets/images/onboarding_map_screen.jpg
    - assets/images/onboarding_screen_2.jpg
    - assets/images/onboarding_screen_4.jpg
    - assets/icons/google.png
    - assets/icons/applepay.png
    - assets/icons/social.png
    - assets/icons/whatsapp.png
    - assets/icons/instagram.png
    - assets/icons/telegram.png
    - assets/icons/gmail.png
    - assets/icons/atmcard.png
    - assets/icons/facebook.png