name: event_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.4.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0

  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/onboarding_community_events.png
    - assets/images/onboarding_illustration.png
    - assets/images/onboarding_map_screen.jpg
    - assets/images/onboarding_screen_2.jpg
    - assets/images/onboarding_screen_4.jpg
